version: "3.9"

services:
  app:
    build:
      context: .
    container_name: grab-fastapi
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on: []
    networks:
      - grab-network
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - grab-network
      
networks:
  grab-network:
    external: true
